#lista = [[URI, Label, Context]
Lista = [
['http://localhost/book#AC001', 'ARQUITECTURA DE COMPUTADORES', 'ARQUITECTURA DE COMPUTADORES is a book.'],
['http://localhost/book#AC002', 'Macroeconomia de economias pequenas y abiertas', 'Macroeconomia de economias pequenas y abiertas is a book.'],
['http://localhost/book#AC003', 'La interpretacion de las culturas', 'La interpretacion de las culturas is a book.'],
['http://localhost/book#AC004', 'Capitanes de la arena', 'Capitanes de la arena is a book.'],
['http://localhost/book#AC005', 'En penumbras', 'En penumbras is a book.'],
['http://localhost/book#AC006', 'El rojo en la pluma del loro', 'El rojo en la pluma del loro is a book.'],
['http://localhost/book#AC007', 'Economia Internacional', 'Economia Internacional is a book.'],
['http://localhost/book#AC008', 'Teoria y Politica', 'Teoria y Politica is a book.'],
['http://localhost/book#AC009', 'LA era del vacio', 'LA era del vacio is a book.'],
['http://localhost/book#AC010', 'Los nombres de la niebla', 'Los nombres de la niebla is a book.'],
['http://localhost/book#ACS001', 'Calidad de Sistemas Informaticos', 'Calidad de Sistemas Informaticos is a book.'],
['http://localhost/book#ACS002', 'Diccionario de la Real Academia Espanola', 'Diccionario de la Real Academia Espanola is a book.'],
['http://localhost/book#ACS003', 'El Tunel', 'El Tunel is a book.'],
['http://localhost/book#ACS004', 'El arte de la guerra', 'El arte de la guerra is a book.'],
['http://localhost/book#ACS005', 'Relato de un naufrago', 'Relato de un naufrago is a book.'],
['http://localhost/book#ACS006', 'Crimen y Castigo', 'Crimen y Castigo is a book.'],
['http://localhost/book#ACS007', 'El mundo de Sofia', 'El mundo de Sofia is a book.'],
['http://localhost/book#ACS008', 'Ensayo sobre la ceguera', 'Ensayo sobre la ceguera is a book.'],
['http://localhost/book#ACS009', 'El principe', 'El principe is a book.'],
['http://localhost/book#ACS010', 'Rebelion en la granja', 'Rebelion en la granja is a book.'],
['http://localhost/book#AD010', 'Administracion de Proyectos', 'Administracion de Proyectos is a book.'],
['http://localhost/book#AD011', 'Administracion de Sistemas de Produccion', 'Administracion de Sistemas de Produccion is a book.'],
['http://localhost/book#AD012', 'Administracion y Arte del Servicio al Cliente', 'Administracion y Arte del Servicio al Cliente is a book.'],
['http://localhost/book#AD013', 'Administracion y Analisis de Puestos', 'Administracion y Analisis de Puestos is a book.'],
['http://localhost/book#AD014', 'Relaciones Laborales y Productivas', 'Relaciones Laborales y Productivas is a book.'],
['http://localhost/book#AD015', 'Pronosticos para Negocios', 'Pronosticos para Negocios is a book.'],
['http://localhost/book#AD016', 'Conversaciones con el Poder', 'Conversaciones con el Poder is a book.'],
['http://localhost/book#AD017', 'Administracion para Emprendedore', 'Administracion para Emprendedore is a book.'],
['http://localhost/book#AD018', 'Klepner Publicidad', 'Klepner Publicidad is a book.'],
['http://localhost/book#AD019', 'Consiga mas', 'Consiga mas is a book.'],
['http://localhost/book#AD020', 'Capacitacion y desarrollo del personal', 'Capacitacion y desarrollo del personal is a book.'],
['http://localhost/book#ADII001', 'Base de Datos', 'Base de Datos is a book.'],
['http://localhost/book#ADII002', 'Berin Alexanderplatz', 'Berin Alexanderplatz is a book.'],
['http://localhost/book#ADII003', 'El idiota', 'El idiota is a book.'],
['http://localhost/book#ADII004', 'Almas muertas', 'Almas muertas is a book.'],
['http://localhost/book#ADII005', 'Gran Serton:Veredas', 'Gran Serton:Veredas is a book.'],
['http://localhost/book#ADII006', 'Hambre', 'Hambre is a book.'],
['http://localhost/book#ADII007', 'El viejo y el mar', 'El viejo y el mar is a book.'],
['http://localhost/book#ADII008', 'Casa de munecas ', 'Casa de munecas  is a book.'],
['http://localhost/book#ADII009', 'Ulises', 'Ulises is a book.'],
['http://localhost/book#ADII010', 'El proceso', 'El proceso is a book.'],
['http://localhost/book#ADII011', 'El castillo', 'El castillo is a book.'],
['http://localhost/book#AL001', 'Matematicas para la Economia', 'Matematicas para la Economia is a book.'],
['http://localhost/book#AL002', 'Economia con Matematicas', 'Economia con Matematicas is a book.'],
['http://localhost/book#AL003', 'Compras un Enfoque estrategico', 'Compras un Enfoque estrategico is a book.'],
['http://localhost/book#AL004', 'La experiencia Starbuks', 'La experiencia Starbuks is a book.'],
['http://localhost/book#AL005', 'Comunicacion organizacional practica', 'Comunicacion organizacional practica is a book.'],
['http://localhost/book#AL006', 'El Arte de la Direccion', 'El Arte de la Direccion is a book.'],
['http://localhost/book#AL007', 'Maestria Profesional', 'Maestria Profesional is a book.'],
['http://localhost/book#AL008', 'Renacer espiritual en la Empresa', 'Renacer espiritual en la Empresa is a book.'],
['http://localhost/book#AN001', 'Comunicacion de las Organizaciones', 'Comunicacion de las Organizaciones is a book.'],
['http://localhost/book#AN002', 'Metodos Numericos para Ingenieros', 'Metodos Numericos para Ingenieros is a book.'],
['http://localhost/book#AN003', 'Fausto', 'Fausto is a book.'],
['http://localhost/book#AN004', 'La Divina Comedia', 'La Divina Comedia is a book.'],
['http://localhost/book#AN005', 'La Guerra y la Paz', 'La Guerra y la Paz is a book.'],
['http://localhost/book#AN006', 'Cumbres Borrascosas', 'Cumbres Borrascosas is a book.'],
['http://localhost/book#AN007', 'Orgullo y Prejuicio', 'Orgullo y Prejuicio is a book.'],
['http://localhost/book#AN008', 'El Retrato de Dorian Gray', 'El Retrato de Dorian Gray is a book.'],
['http://localhost/book#AN009', 'Los viajes de Golliver', 'Los viajes de Golliver is a book.'],
['http://localhost/book#AR001', 'Tener y ser', 'Tener y ser is a book.'],
['http://localhost/book#AR002', 'Psicologia Social', 'Psicologia Social is a book.'],
['http://localhost/book#AR003', 'Humanismo y gestion de salud', 'Humanismo y gestion de salud is a book.'],
['http://localhost/book#AUDII001', 'Bostan', 'Bostan is a book.'],
['http://localhost/book#AUDII002', 'Tiempo de migrar al noche', 'Tiempo de migrar al noche is a book.'],
['http://localhost/book#AUDII003', 'Ceguera', 'Ceguera is a book.'],
['http://localhost/book#AUDII004', 'Hamlet', 'Hamlet is a book.'],
['http://localhost/book#AUDII005', 'El rey Lear', 'El rey Lear is a book.'],
['http://localhost/book#B001', 'BIOQUIMICA', 'BIOQUIMICA is a book.'],
['http://localhost/book#B002', 'Cuentos Completos', 'Cuentos Completos is a book.'],
['http://localhost/book#B003', 'LA tia Julia y el Escribidor', 'LA tia Julia y el Escribidor is a book.'],
['http://localhost/book#B004', 'El Amor las mujeres y la vida', 'El Amor las mujeres y la vida is a book.'],
['http://localhost/book#B005', 'LA guerra del fin del mundo', 'LA guerra del fin del mundo is a book.'],
['http://localhost/book#B006', 'Ficciones', 'Ficciones is a book.'],
['http://localhost/book#BDA001', 'REDES DITRIBUIDAS', 'REDES DITRIBUIDAS is a book.'],
['http://localhost/book#BDA002', 'Sobre la teoria de la Ansiedad y la culpa', 'Sobre la teoria de la Ansiedad y la culpa is a book.'],
['http://localhost/book#BDA003', 'Intitucion de Analisis', 'Intitucion de Analisis is a book.'],
['http://localhost/book#BDA004', 'Seleccioon de Articulos consulta y referencia', 'Seleccioon de Articulos consulta y referencia is a book.'],
['http://localhost/book#BDA005', 'Un aporte a la eficiencia personal', 'Un aporte a la eficiencia personal is a book.'],
['http://localhost/book#BDA006', 'Hormonas', 'Hormonas is a book.'],
['http://localhost/book#BDA007', 'Practica Clinica', 'Practica Clinica is a book.'],
['http://localhost/book#BII001', 'FUNDAMENTOS DE PROGRAMACION C', 'FUNDAMENTOS DE PROGRAMACION C is a book.'],
['http://localhost/book#BII002', 'En busca del tiempo perdido', 'En busca del tiempo perdido is a book.'],
['http://localhost/book#BII003', 'Gargantua y Pantagruel', 'Gargantua y Pantagruel is a book.'],
['http://localhost/book#CAL001', 'Calculo I', 'Calculo I is a book.'],
['http://localhost/book#CAL002', 'La Biblia', 'La Biblia is a book.'],
['http://localhost/book#CAL003', 'Cien Anioos de Soldedad', 'Cien Anioos de Soldedad is a book.'],
['http://localhost/book#CAL004', 'La casa de los espiritus', 'La casa de los espiritus is a book.'],
['http://localhost/book#CAL005', 'El Conde de Montecristo', 'El Conde de Montecristo is a book.'],
['http://localhost/book#CAL006', 'La Metamorfosis', 'La Metamorfosis is a book.'],
['http://localhost/book#CAL007', 'La sombra del viento', 'La sombra del viento is a book.'],
['http://localhost/book#CAL008', 'El Psicoanalista', 'El Psicoanalista is a book.'],
['http://localhost/book#CAL009', 'El Secreto', 'El Secreto is a book.'],
['http://localhost/book#CAL010', 'El nombre de  rosa', 'El nombre de  rosa is a book.'],
['http://localhost/book#CALII001', 'Rojo y Negro', 'Rojo y Negro is a book.'],
['http://localhost/book#CALII002', 'Ramayana', 'Ramayana is a book.'],
['http://localhost/book#CALII003', 'Eneida', 'Eneida is a book.'],
['http://localhost/book#CALII004', 'DISEnO WEB', 'DISEnO WEB is a book.'],
['http://localhost/book#CAV001', 'La conciencia de Zeno', 'La conciencia de Zeno is a book.'],
['http://localhost/book#CAV002', 'Guerra y paz', 'Guerra y paz is a book.'],
['http://localhost/book#CAV003', 'Ana Karenina', 'Ana Karenina is a book.'],
['http://localhost/book#CAV004', 'La muerte de Ivan Ilich', 'La muerte de Ivan Ilich is a book.'],
['http://localhost/book#CAV005', 'Las aventuras de Huckleberry Finn', 'Las aventuras de Huckleberry Finn is a book.'],
['http://localhost/book#CB001', 'REALIDAD NACIONAL', 'REALIDAD NACIONAL is a book.'],
['http://localhost/book#CB002', 'Hojas de Hierba', 'Hojas de Hierba is a book.'],
['http://localhost/book#CCB001', 'Harry Potter Serie', 'Harry Potter Serie is a book.'],
['http://localhost/book#CCB002', 'Don Quijjojte de la Manca', 'Don Quijjojte de la Manca is a book.'],
['http://localhost/book#CCB003', 'El principito', 'El principito is a book.'],
['http://localhost/book#CE001', 'Fundacion', 'Fundacion is a book.'],
['http://localhost/book#CE002', 'GESTION DEL COMERCIO EXTERIOR', 'GESTION DEL COMERCIO EXTERIOR is a book.'],
['http://localhost/book#CE003', 'Cronicas Marcianas', 'Cronicas Marcianas is a book.'],
['http://localhost/book#CE004', 'El tambor de hojalta', 'El tambor de hojalta is a book.'],
['http://localhost/book#CE005', 'La conjura de los necios', 'La conjura de los necios is a book.'],
['http://localhost/book#CE006', 'Toki Blues', 'Toki Blues is a book.'],
['http://localhost/book#CERII001', 'LOGICA MATEMATCA', 'LOGICA MATEMATCA is a book.'],
['http://localhost/book#CERII002', 'Lolita', 'Lolita is a book.'],
['http://localhost/book#CERII003', 'Libro del desasosiego', 'Libro del desasosiego is a book.'],
['http://localhost/book#CERII004', 'Cuenos', 'Cuenos is a book.'],
['http://localhost/book#CI001', 'El diario de Ana Frank', 'El diario de Ana Frank is a book.'],
['http://localhost/book#CI002', 'El Alquimista ', 'El Alquimista  is a book.'],
['http://localhost/book#CI003', 'El Codigo Da Vinci', 'El Codigo Da Vinci is a book.'],
['http://localhost/book#CI004', 'El Perfume', 'El Perfume is a book.'],
['http://localhost/book#CI005', 'El Senioor de los Anillos', 'El Senioor de los Anillos is a book.'],
['http://localhost/book#CI006', 'El amor en tiempos de colera', 'El amor en tiempos de colera is a book.'],
['http://localhost/book#CI007', 'Cronica de una muerte anunciada', 'Cronica de una muerte anunciada is a book.'],
['http://localhost/book#CI008', 'Angeles y Demonios', 'Angeles y Demonios is a book.'],
['http://localhost/book#CMOG001', 'COMUNICACION ORGANIZACIONAL INTERNA', 'COMUNICACION ORGANIZACIONAL INTERNA is a book.'],
['http://localhost/book#CMOG002', 'El Anti Edipo', 'El Anti Edipo is a book.'],
['http://localhost/book#CMOG003', 'La gesta del marrano', 'La gesta del marrano is a book.'],
['http://localhost/book#CMOG004', 'LA imagen de la vida humana', 'LA imagen de la vida humana is a book.'],
['http://localhost/book#CMOG005', 'Las palabras y las cosas', 'Las palabras y las cosas is a book.'],
['http://localhost/book#CO001', 'COMPORTAMIENTO ORGANIZACIONAL', 'COMPORTAMIENTO ORGANIZACIONAL is a book.'],
['http://localhost/book#CO002', 'El libro del abrazos', 'El libro del abrazos is a book.'],
['http://localhost/book#CO003', 'El pendulo de Foucault', 'El pendulo de Foucault is a book.'],
['http://localhost/book#CO004', 'Final de Juego', 'Final de Juego is a book.'],
['http://localhost/book#CO005', 'Diccionario Filosofico', 'Diccionario Filosofico is a book.'],
['http://localhost/book#CO006', 'El libro de las ilusiones', 'El libro de las ilusiones is a book.'],
['http://localhost/book#CO007', 'Cronicas del angel gris', 'Cronicas del angel gris is a book.'],
['http://localhost/book#CO008', 'Mujeres que corren con los lobos', 'Mujeres que corren con los lobos is a book.'],
['http://localhost/book#CO009', 'Antologia de la Literatura Fantasica', 'Antologia de la Literatura Fantasica is a book.'],
['http://localhost/book#CO010', 'Cronica del pajaro que da cuerda al mundo', 'Cronica del pajaro que da cuerda al mundo is a book.'],
['http://localhost/book#CO011', 'La borra del cafe', 'La borra del cafe is a book.'],
['http://localhost/book#CO012', 'La historia del Arte', 'La historia del Arte is a book.'],
['http://localhost/book#CO013', 'Los detectives Salvajes', 'Los detectives Salvajes is a book.'],
['http://localhost/book#CONT001', 'CONTABILIDAD GENERAL (INTRODUCCIoN)', 'CONTABILIDAD GENERAL (INTRODUCCIoN) is a book.'],
['http://localhost/book#CONT002', 'Cuentos Chinos', 'Cuentos Chinos is a book.'],
['http://localhost/book#CONT003', 'Andamios', 'Andamios is a book.'],
['http://localhost/book#CONT004', 'Historia del siglo XX', 'Historia del siglo XX is a book.'],
['http://localhost/book#CONT005', 'En el camino', 'En el camino is a book.'],
['http://localhost/book#CONT006', 'La consagracion de la primavera', 'La consagracion de la primavera is a book.'],
['http://localhost/book#CONT007', 'Codigo Civil', 'Codigo Civil is a book.'],
['http://localhost/book#CONT008', 'Las cartas que no llegaron', 'Las cartas que no llegaron is a book.'],
['http://localhost/book#DEC001', 'PC: ACTUALIZACIoN Y MANTENIMIENTO', 'PC: ACTUALIZACIoN Y MANTENIMIENTO is a book.'],
['http://localhost/book#DEC002', 'Un mundo Feliz', 'Un mundo Feliz is a book.'],
['http://localhost/book#DEC003', 'Rayuela', 'Rayuela is a book.'],
['http://localhost/book#DEC004', 'Mi planta de naranja lima', 'Mi planta de naranja lima is a book.'],
['http://localhost/book#DEC005', 'George 1984', 'George 1984 is a book.'],
['http://localhost/book#DEC006', 'Paula', 'Paula is a book.'],
['http://localhost/book#DIBT001', 'Beloved', 'Beloved is a book.'],
['http://localhost/book#DIBT002', 'Genji Monogatari', 'Genji Monogatari is a book.'],
['http://localhost/book#DIBT003', 'Ell hombre sin atributos', 'Ell hombre sin atributos is a book.'],
['http://localhost/book#DR001', 'EL DERECHO ROMANO EN LA UNIVERSIDAD DEL SIGLO XXI', 'EL DERECHO ROMANO EN LA UNIVERSIDAD DEL SIGLO XXI is a book.'],
['http://localhost/book#DR002', 'No logo el poder del las marcas', 'No logo el poder del las marcas is a book.'],
['http://localhost/book#DR003', 'Entrevista con la historia', 'Entrevista con la historia is a book.'],
['http://localhost/book#DR004', 'El Astillero', 'El Astillero is a book.'],
['http://localhost/book#DR005', 'Apocalipticos E integrados', 'Apocalipticos E integrados is a book.'],
['http://localhost/book#DR006', 'Poesia completa', 'Poesia completa is a book.'],
['http://localhost/book#EA001', 'Al faro', 'Al faro is a book.'],
['http://localhost/book#EA002', 'LA equivocacion del sujeto supuesto a saber', 'LA equivocacion del sujeto supuesto a saber is a book.'],
['http://localhost/book#EA003', 'El Destete', 'El Destete is a book.'],
['http://localhost/book#EA004', 'El desarrollo de un nino', 'El desarrollo de un nino is a book.'],
['http://localhost/book#EA005', 'MINERIA DE DATOS', 'MINERIA DE DATOS is a book.'],
['http://localhost/book#EA006', 'Mas alla del principio del placer', 'Mas alla del principio del placer is a book.'],
['http://localhost/book#EA007', 'El hombre en busca de sentido', 'El hombre en busca de sentido is a book.'],
['http://localhost/book#EA008', 'Administracion en servicios de enfermeria', 'Administracion en servicios de enfermeria is a book.'],
['http://localhost/book#EA009', 'INGENIERIA DE SOFTWARE', 'INGENIERIA DE SOFTWARE is a book.'],
['http://localhost/book#EA010', 'Comunicacion herramienta para el trabajo', 'Comunicacion herramienta para el trabajo is a book.'],
['http://localhost/book#EST001', 'ESTADiSTICA', 'ESTADiSTICA is a book.'],
['http://localhost/book#EST002', 'Donde los hombres cantan', 'Donde los hombres cantan is a book.'],
['http://localhost/book#EST003', 'LA lista de los nombres olvidados', 'LA lista de los nombres olvidados is a book.'],
['http://localhost/book#EST004', 'Mucho mas que un nombre', 'Mucho mas que un nombre is a book.'],
['http://localhost/book#EST005', 'El temor de un hombre sabio', 'El temor de un hombre sabio is a book.'],
['http://localhost/book#EST006', 'Juego de Tronos', 'Juego de Tronos is a book.'],
['http://localhost/book#FIS001', 'INGENIERiA DEL SOFTWARE. UN ENFOQUE PRaCTICO', 'INGENIERiA DEL SOFTWARE. UN ENFOQUE PRaCTICO is a book.'],
['http://localhost/book#FIS002', 'Las malas palabras', 'Las malas palabras is a book.'],
['http://localhost/book#FIS003', 'Los 8 nombres de Picasso', 'Los 8 nombres de Picasso is a book.'],
['http://localhost/book#FIS004', 'Letras', 'Letras is a book.'],
['http://localhost/book#FIS005', 'Un nombre distinto', 'Un nombre distinto is a book.'],
['http://localhost/book#FIS006', 'Los nombres del aire', 'Los nombres del aire is a book.'],
['http://localhost/book#FIS007', 'Oscuridad', 'Oscuridad is a book.'],
['http://localhost/book#FIS008', 'Clases de Literatura', 'Clases de Literatura is a book.'],
['http://localhost/book#FIS009', 'INTELIGENCIA ARTIFICIAL. UN ENFOQUE MODERNO', 'INTELIGENCIA ARTIFICIAL. UN ENFOQUE MODERNO is a book.'],
['http://localhost/book#FIS010', 'Los nombres del arcoiris', 'Los nombres del arcoiris is a book.'],
['http://localhost/book#FIS011', 'Detras de ti', 'Detras de ti is a book.'],
['http://localhost/book#FM001', 'Los tres Mosqueteros', 'Los tres Mosqueteros is a book.'],
['http://localhost/book#FM002', 'La piel de Zapa', 'La piel de Zapa is a book.'],
['http://localhost/book#FM003', 'La vida es Suenioo', 'La vida es Suenioo is a book.'],
['http://localhost/book#FM004', 'La Iliada', 'La Iliada is a book.'],
['http://localhost/book#FM005', 'La Odisea', 'La Odisea is a book.'],
['http://localhost/book#FPRG001', 'FUNDAMENTOS DE PROGRAMACION APRENDIZAJE ACTIVO BASADO EN CASOS', 'FUNDAMENTOS DE PROGRAMACION APRENDIZAJE ACTIVO BASADO EN CASOS is a book.'],
['http://localhost/book#FPRG002', 'Hattler', 'Hattler is a book.'],
['http://localhost/book#FPRG003', 'Lo que el viento se llevo', 'Lo que el viento se llevo is a book.'],
['http://localhost/book#FPRG004', 'Lamame Bombon', 'Lamame Bombon is a book.'],
['http://localhost/book#FTEC001', 'Shakuntala', 'Shakuntala is a book.'],
['http://localhost/book#FTEC002', 'DIAGNOSTICO Y MANTENIMIENTO DE COMPUTADORAS', 'DIAGNOSTICO Y MANTENIMIENTO DE COMPUTADORAS is a book.'],
['http://localhost/book#FTEC003', 'Hijos y Amantes', 'Hijos y Amantes is a book.'],
['http://localhost/book#FTEC004', 'Los Buddenbrook', 'Los Buddenbrook is a book.'],
['http://localhost/book#FTEC005', 'La montana magica', 'La montana magica is a book.'],
['http://localhost/book#FTEC006', 'Moby Dick', 'Moby Dick is a book.'],
['http://localhost/book#FTEC007', 'LA historia', 'LA historia is a book.'],
['http://localhost/book#GA001', 'SISTEMAS DIGITALES', 'SISTEMAS DIGITALES is a book.'],
['http://localhost/book#GA002', 'La senora Dalloway', 'La senora Dalloway is a book.'],
['http://localhost/book#GA003', 'Memorias de Adriano', 'Memorias de Adriano is a book.'],
['http://localhost/book#GA004', 'Psicologia Cognositiva', 'Psicologia Cognositiva is a book.'],
['http://localhost/book#GC001', 'ALGORITMOS ', 'ALGORITMOS  is a book.'],
['http://localhost/book#GCI001', 'Psicologia Anormal', 'Psicologia Anormal is a book.'],
['http://localhost/book#GCI002', 'Psicologia Experimental', 'Psicologia Experimental is a book.'],
['http://localhost/book#GCI003', 'Psicologia de Transferencia', 'Psicologia de Transferencia is a book.'],
['http://localhost/book#GCI004', 'LA practica de la inteligencia Emocional', 'LA practica de la inteligencia Emocional is a book.'],
['http://localhost/book#GCI005', 'MINERIA DE DATOS', 'MINERIA DE DATOS is a book.'],
['http://localhost/book#GCI006', 'Hipertension Arterial', 'Hipertension Arterial is a book.'],
['http://localhost/book#GCI007', 'Imagenologia', 'Imagenologia is a book.'],
['http://localhost/book#GCI008', 'Manual tecnicas quirurgicas', 'Manual tecnicas quirurgicas is a book.'],
['http://localhost/book#GCI009', 'Pediatria', 'Pediatria is a book.'],
['http://localhost/book#GEM001', 'GESTIoN DE LA INNOVACIoN EMPRESARIAL', 'GESTIoN DE LA INNOVACIoN EMPRESARIAL is a book.'],
['http://localhost/book#GEM002', 'Me llaman Magdalena', 'Me llaman Magdalena is a book.'],
['http://localhost/book#GEM003', 'Alma Alga', 'Alma Alga is a book.'],
['http://localhost/book#GEM004', 'Noches de Tormenta', 'Noches de Tormenta is a book.'],
['http://localhost/book#GEM005', 'Entre las Cenizas', 'Entre las Cenizas is a book.'],
['http://localhost/book#GEM006', 'Recuperar la Ilusion', 'Recuperar la Ilusion is a book.'],
['http://localhost/book#GEP001', 'FUNDAMENTOS DE PERIODISMO CIENTiFICO Y DIVULGACIoN MEDIATICA', 'FUNDAMENTOS DE PERIODISMO CIENTiFICO Y DIVULGACIoN MEDIATICA is a book.'],
['http://localhost/book#GEP002', 'Los nombres del dia', 'Los nombres del dia is a book.'],
['http://localhost/book#GEP003', 'LA Cumbina de Roma', 'LA Cumbina de Roma is a book.'],
['http://localhost/book#GP001', 'Guia de los Fundamentos de la Direccion de Proyectos', 'Guia de los Fundamentos de la Direccion de Proyectos is a book.'],
['http://localhost/book#GP002', 'Nombre de Mujer', 'Nombre de Mujer is a book.'],
['http://localhost/book#GP003', 'Pensar de la historia', 'Pensar de la historia is a book.'],
['http://localhost/book#GP004', 'Carton y Papeles', 'Carton y Papeles is a book.'],
['http://localhost/book#GTUR001', 'Los endemoniados', 'Los endemoniados is a book.'],
['http://localhost/book#GTUR002', 'Los hermanos Karamazon', 'Los hermanos Karamazon is a book.'],
['http://localhost/book#GTUR003', 'Middiemarch', 'Middiemarch is a book.'],
['http://localhost/book#GTUR004', 'El hombre invisible', 'El hombre invisible is a book.'],
['http://localhost/book#GTUR005', 'Medea', 'Medea is a book.'],
['http://localhost/book#GTUR006', 'Absalom', 'Absalom is a book.'],
['http://localhost/book#GTUR007', 'REDES Y TELECOMUNICACIONES', 'REDES Y TELECOMUNICACIONES is a book.'],
['http://localhost/book#GTUR008', 'El ruido y la furia', 'El ruido y la furia is a book.'],
['http://localhost/book#GTUR009', 'Madame Bovary', 'Madame Bovary is a book.'],
['http://localhost/book#GTUR010', 'La educacion sentimental', 'La educacion sentimental is a book.'],
['http://localhost/book#GTUR011', 'Romance Gitano', 'Romance Gitano is a book.'],
['http://localhost/book#GU001', 'ELECTRONICA', 'ELECTRONICA is a book.'],
['http://localhost/book#IESC001', 'LIDERAZGO Y CREATIVIDAD', 'LIDERAZGO Y CREATIVIDAD is a book.'],
['http://localhost/book#IESC002', 'Otelo', 'Otelo is a book.'],
['http://localhost/book#IESC003', 'Edipo Rey', 'Edipo Rey is a book.'],
['http://localhost/book#IESC004', 'Vida y Opiniones del caballero Tristram Shandy', 'Vida y Opiniones del caballero Tristram Shandy is a book.'],
['http://localhost/book#IJ001', 'INVESTIGACIoN Y DOCUMENTACIoN JURiDICA', 'INVESTIGACIoN Y DOCUMENTACIoN JURiDICA is a book.'],
['http://localhost/book#IJ002', 'La urdimbre del tiempo', 'La urdimbre del tiempo is a book.'],
['http://localhost/book#IJ003', 'El Marquez de Sade', 'El Marquez de Sade is a book.'],
['http://localhost/book#IJ004', 'Viaje al centro de la Tierra', 'Viaje al centro de la Tierra is a book.'],
['http://localhost/book#IJ005', 'Procecsos Quimicos', 'Procecsos Quimicos is a book.'],
['http://localhost/book#IJ006', 'El nombre falso de un ser importante', 'El nombre falso de un ser importante is a book.'],
['http://localhost/book#IOP001', 'INVESTIGACIoN OPERATIVA: MODELOS DETERMINiSTICOS Y ESTOCaSTICOS', 'INVESTIGACIoN OPERATIVA: MODELOS DETERMINiSTICOS Y ESTOCaSTICOS is a book.'],
['http://localhost/book#IOP002', 'Estrellas', 'Estrellas is a book.'],
['http://localhost/book#IOP003', 'Nombres y Animales', 'Nombres y Animales is a book.'],
['http://localhost/book#IOP004', 'Poemas de Gilgamesh', 'Poemas de Gilgamesh is a book.'],
['http://localhost/book#IOP005', 'Las mil y una noches', 'Las mil y una noches is a book.'],
['http://localhost/book#IOP006', 'Saga de Njai', 'Saga de Njai is a book.'],
['http://localhost/book#IOP007', 'Todo se desmorona', 'Todo se desmorona is a book.'],
['http://localhost/book#IOP008', 'Cuentos Infantiles', 'Cuentos Infantiles is a book.'],
['http://localhost/book#MAT001', 'JAQUE A LAS MATEMaTICAS', 'JAQUE A LAS MATEMaTICAS is a book.'],
['http://localhost/book#MAT002', 'Siddharta', 'Siddharta is a book.'],
['http://localhost/book#MAT003', 'El lobo estepario', 'El lobo estepario is a book.'],
['http://localhost/book#MAT004', 'Las venas abiertas de America Latina', 'Las venas abiertas de America Latina is a book.'],
['http://localhost/book#MAT005', 'Cuentas de Amor, de ocura y de muerte', 'Cuentas de Amor, de ocura y de muerte is a book.'],
['http://localhost/book#MAT006', 'Asi hablo Zaratustra', 'Asi hablo Zaratustra is a book.'],
['http://localhost/book#MAT007', 'La tregua', 'La tregua is a book.'],
['http://localhost/book#MAT008', 'Obras Completas', 'Obras Completas is a book.'],
['http://localhost/book#MAT009', 'La insoportable levedad del ser', 'La insoportable levedad del ser is a book.'],
['http://localhost/book#MAT010', 'El hombre que calculaba', 'El hombre que calculaba is a book.'],
['http://localhost/book#MAT011', 'El Aleph', 'El Aleph is a book.'],
['http://localhost/book#MATII001', 'El sonido de la montana ', 'El sonido de la montana  is a book.'],
['http://localhost/book#MATII002', 'Zorba, el griego', 'Zorba, el griego is a book.'],
['http://localhost/book#MATII003', 'Gente Independiente', 'Gente Independiente is a book.'],
['http://localhost/book#MATII004', 'Poemas', 'Poemas is a book.'],
['http://localhost/book#MATII005', 'El cuaderno dorada', 'El cuaderno dorada is a book.'],
['http://localhost/book#MATII006', 'Pippi Calzasiargas', 'Pippi Calzasiargas is a book.'],
['http://localhost/book#MATII007', 'Diario de un Loco', 'Diario de un Loco is a book.'],
['http://localhost/book#MATII008', 'Hijos de nuestro barrio', 'Hijos de nuestro barrio is a book.'],
['http://localhost/book#MATII009', 'Ensayos', 'Ensayos is a book.'],
['http://localhost/book#MC001', 'METODOS CUANTITATIVOS PARA LOS NEGOCIOS', 'METODOS CUANTITATIVOS PARA LOS NEGOCIOS is a book.'],
['http://localhost/book#MC002', 'Molloy', 'Molloy is a book.'],
['http://localhost/book#MC003', 'Malones muere', 'Malones muere is a book.'],
['http://localhost/book#MC004', 'El Innombrable', 'El Innombrable is a book.'],
['http://localhost/book#MC005', 'Una trilogia', 'Una trilogia is a book.'],
['http://localhost/book#MDC001', 'MATEMATICAS DISCRETAS', 'MATEMATICAS DISCRETAS is a book.'],
['http://localhost/book#MDC002', 'Fahrenheit 451', 'Fahrenheit 451 is a book.'],
['http://localhost/book#MDC003', 'El Silmarillion', 'El Silmarillion is a book.'],
['http://localhost/book#MDC004', 'Los siete habitos de la gente altamente efectiva', 'Los siete habitos de la gente altamente efectiva is a book.'],
['http://localhost/book#MDC005', 'El guardian entre el centero', 'El guardian entre el centero is a book.'],
['http://localhost/book#MDC006', 'Por quien doblan las campanas', 'Por quien doblan las campanas is a book.'],
['http://localhost/book#MDC007', 'A sangre fria', 'A sangre fria is a book.'],
['http://localhost/book#MI001', 'Pedro Paramo', 'Pedro Paramo is a book.'],
['http://localhost/book#MI002', 'Masnavi', 'Masnavi is a book.'],
['http://localhost/book#MI003', 'Hijos de la media noche', 'Hijos de la media noche is a book.'],
['http://localhost/book#MUL001', 'Introduccion a la Programacion Paralela', 'Introduccion a la Programacion Paralela is a book.'],
['http://localhost/book#MUL002', 'Decameron', 'Decameron is a book.'],
['http://localhost/book#MUL003', 'El Extranjero', 'El Extranjero is a book.'],
['http://localhost/book#MUL004', 'Poemas', 'Poemas is a book.'],
['http://localhost/book#MUL005', 'Viaje al fin de la noche', 'Viaje al fin de la noche is a book.'],
['http://localhost/book#MUL006', 'Los cuentos de Caterbury', 'Los cuentos de Caterbury is a book.'],
['http://localhost/book#MVL001', 'LOS MERCADOS DE VALORES', 'LOS MERCADOS DE VALORES is a book.'],
['http://localhost/book#MVL002', 'Divina Comedia', 'Divina Comedia is a book.'],
['http://localhost/book#MVL003', 'Papa Goriot', 'Papa Goriot is a book.'],
['http://localhost/book#MVL004', 'LOS MERCADOS DE VALORES', 'LOS MERCADOS DE VALORES is a book.'],
['http://localhost/book#SBC001', 'El arte de amar', 'El arte de amar is a book.'],
['http://localhost/book#SBC002', 'El dogma de Cristo', 'El dogma de Cristo is a book.'],
['http://localhost/book#SBC003', 'Grafologia Elemental', 'Grafologia Elemental is a book.'],
['http://localhost/book#SBC004', 'Historia de la locura en epoca clasica', 'Historia de la locura en epoca clasica is a book.'],
['http://localhost/book#SBC005', 'Historia de la sexualidad', 'Historia de la sexualidad is a book.'],
['http://localhost/book#SBC006', 'Abdomen Agudo', 'Abdomen Agudo is a book.'],
['http://localhost/book#TAC001', 'CONSTRUCCIoN DE COMPILADORES. PRINCIPIOS Y PRaCTICA', 'CONSTRUCCIoN DE COMPILADORES. PRINCIPIOS Y PRaCTICA is a book.'],
['http://localhost/book#TAC002', 'Relatos Cortos', 'Relatos Cortos is a book.'],
['http://localhost/book#TAC003', 'Nostromo', 'Nostromo is a book.'],
['http://localhost/book#TAC004', 'Grandes Esperanzas', 'Grandes Esperanzas is a book.'],
['http://localhost/book#TAC005', 'Jaccquess el fatalista', 'Jaccquess el fatalista is a book.'],
['http://localhost/book#AD001', 'Manual practico de Administracion', 'Manual practico de Administracion is a book.'],
['http://localhost/book#AD002', 'Practicas de Administracion', 'Practicas de Administracion is a book.'],
['http://localhost/book#AD003', 'Administracion de Sistemas', 'Administracion de Sistemas is a book.'],
['http://localhost/book#AD004', 'Administracion de Empresas', 'Administracion de Empresas is a book.'],
['http://localhost/book#AD005', 'Negocios con Administracion ', 'Negocios con Administracion  is a book.'],
['http://localhost/book#AD006', 'Planes de Administracion ', 'Planes de Administracion  is a book.'],
['http://localhost/book#AD007', 'Administracion de Procesos', 'Administracion de Procesos is a book.'],
['http://localhost/book#AD008', 'Direccion Estrategica', 'Direccion Estrategica is a book.'],
['http://localhost/book#AD009', 'Comportamiento del consumidor y estrategias de mejoras', 'Comportamiento del consumidor y estrategias de mejoras is a book.'],

]